title: Nicolas Neupokoev
url: "http://nicolas.zz.mu"
twitter_username: stakanmartini
github_username:  mikolasan
#source: _source
destination: _site

# Handling Reading
exclude: ['Gemfile','Gemfile.lock','Rakefile','.git']

# Conversion
highlighter: pygments
excerpt_separator: <!--more-->

# Outputting
permalink: /:categories/:title
paginate: 4


